# name: Deploy to Production

# on:
#   push:
#     branches: [yujo11]

# jobs:
#   deploy:
#     name: Build, Deploy to S3 bucket
#     runs-on: [ubuntu-latest]

#     steps:
#       - uses: actions/checkout@v2

#       - name: Transfer to S3 for serving static
#         uses: jakejarvis/s3-sync-action@master
#         # with:
#         #   args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: "apple-clone-yujo"
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
#           AWS_REGION: "ap-northeast-2"
#           SOURCE_DIR: "src"

name: S3 CI/CD

on:
  push:
    branches: [yujo11]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: S3 Sync
        run: aws s3 sync . s3://apple-clone-yujo --region "ap-northeast-2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "src"
