name: S3 CI/CD

on:
  push:
    branches: [yujo11]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: S3 Sync
        run: aws s3 sync src s3://apple-clone-yujo --region "ap-northeast-2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "src"
